/**
 * Xray CLI - Enrichment Markdown Module
 *
 * Pure markdown builders/splicers for `test enrich`. Precondition association
 * and Test Set membership are Xray-internal — they are NOT Jira issue links,
 * so `scripts/sync-jira-issues.ts` (Jira REST) cannot see them. This module
 * renders that Xray-only data as a delimited section appended to each synced
 * `TEST-<KEY>-<slug>.md`, plus a per-Test-Set index file.
 *
 * Everything here is pure (string in, string out) so idempotency is testable
 * without Xray credentials. The command wrapper owns fs + GraphQL.
 */

// Markers delimit the generated block so a re-run REPLACES instead of appends.
// HTML comments render invisibly in markdown viewers and cannot collide with
// the sync's own output (sync never emits HTML comments).
export const ENRICH_BEGIN = '<!-- xray-enrich:begin -->';
export const ENRICH_END = '<!-- xray-enrich:end -->';

export interface EnrichmentPrecondition {
  key: string
  summary?: string
  type?: string
  definition?: string
}

export interface EnrichmentTestSet {
  key: string
  summary?: string
}

export interface TestEnrichment {
  preconditions: EnrichmentPrecondition[]
  testSets: EnrichmentTestSet[]
}

/**
 * Extract the Jira key from a synced Test filename.
 * `TEST-BK-477-some-slug.md` -> `BK-477`. Returns null for anything that is
 * not a synced Test file (README, templates, hand-authored notes).
 */
export function extractTestKey(filename: string): string | null {
  const m = /^TEST-([A-Z][A-Z0-9_]*-\d+)(?:-.*)?\.md$/.exec(filename);
  return m ? m[1] : null;
}

/**
 * Strip our own markers out of remote-sourced text (summaries, definitions).
 * If a Precondition definition contained the literal end marker, the next
 * splice would cut the block short — sanitizing preserves the idempotency
 * invariant no matter what lives in Xray.
 */
function stripMarkers(text: string): string {
  return text.replaceAll(ENRICH_BEGIN, '').replaceAll(ENRICH_END, '');
}

/** `[KEY](host/browse/KEY)` when a Jira host is known, bold key otherwise. */
function linkTo(key: string, jiraBaseUrl: string | null): string {
  return jiraBaseUrl ? `[${key}](${jiraBaseUrl}/browse/${key})` : `**${key}**`;
}

/** Sort by numeric suffix so output order never depends on Xray's ordering. */
function byKey<T extends { key: string }>(items: T[]): T[] {
  return [...items].sort((a, b) => {
    const na = Number.parseInt(a.key.split('-').pop() || '0', 10);
    const nb = Number.parseInt(b.key.split('-').pop() || '0', 10);
    return na - nb || a.key.localeCompare(b.key);
  });
}

/**
 * Render the full delimited section for one Test.
 *
 * Preconditions are INLINED (type + definition), not referenced: the Test file
 * must stay self-contained — a reader should see how to set the Test up
 * without opening a second file. A Precondition shared by N Tests is
 * duplicated across those N files on purpose; these are regenerated caches,
 * so the copies cannot drift.
 *
 * Deliberately contains no timestamp: identical Xray data must produce a
 * byte-identical section, or every run would dirty every file.
 */
export function buildEnrichmentSection(enrichment: TestEnrichment, jiraBaseUrl: string | null): string {
  const lines: string[] = [
    ENRICH_BEGIN,
    '',
    '---',
    '',
    '## Xray Associations',
    '',
    '> Preconditions and Test Set membership are Xray-internal (not Jira issue links), so `sync-jira-issues` cannot mirror them. Generated by `bun xray test enrich` — re-runs replace this section. Do not edit by hand.',
    '',
    '### Preconditions',
    '',
  ];

  if (enrichment.preconditions.length === 0) {
    lines.push('_None — this Test has no Preconditions in Xray._', '');
  }
  else {
    for (const pre of byKey(enrichment.preconditions)) {
      const summary = pre.summary ? ` — ${stripMarkers(pre.summary)}` : '';
      lines.push(`#### ${linkTo(pre.key, jiraBaseUrl)}${summary}`, '');
      if (pre.type) {
        lines.push(`- **Type:** ${pre.type}`, '');
      }
      if (pre.definition) {
        // Blockquoted so a definition with its own headings cannot restructure
        // the host document.
        for (const defLine of stripMarkers(pre.definition).split('\n')) {
          lines.push(defLine ? `> ${defLine}` : '>');
        }
        lines.push('');
      }
      else {
        lines.push('_No definition recorded in Xray._', '');
      }
    }
  }

  lines.push('### Test Sets', '');

  if (enrichment.testSets.length === 0) {
    lines.push('_None — this Test belongs to no Test Set._', '');
  }
  else {
    for (const set of byKey(enrichment.testSets)) {
      const summary = set.summary ? ` — ${stripMarkers(set.summary)}` : '';
      lines.push(`- ${linkTo(set.key, jiraBaseUrl)}${summary} (members: \`test-sets/${set.key}.md\`)`);
    }
    lines.push('');
  }

  lines.push(ENRICH_END);
  return lines.join('\n');
}

/**
 * Insert or replace the delimited section in a Test markdown document.
 *
 * Idempotency: when both markers are present the block (markers included) is
 * swapped for the new section and the surrounding bytes are untouched; when
 * absent, the section is appended after exactly one blank line. Appending
 * then re-splicing the same data yields the identical document.
 */
export function spliceEnrichmentSection(markdown: string, section: string): string {
  const begin = markdown.indexOf(ENRICH_BEGIN);
  const end = markdown.indexOf(ENRICH_END);

  if (begin !== -1 && end > begin) {
    return markdown.slice(0, begin) + section + markdown.slice(end + ENRICH_END.length);
  }

  // No (valid) block yet — append. Trailing whitespace is normalized so the
  // append point is stable regardless of how many newlines the sync left.
  return `${markdown.replace(/\s*$/, '')}\n\n${section}\n`;
}

/**
 * Render the members index for one Test Set: `test-sets/<KEY>.md`.
 *
 * Test Sets are metadata, not folders — a Set can span Stories, so nesting its
 * Tests under any single Story folder would force the "pick one location"
 * problem the PBI tree design rejected. Membership lives in each Test file
 * (section above) and is aggregated here for the Set-first view.
 */
export function buildTestSetIndexMarkdown(
  set: EnrichmentTestSet,
  members: Array<{ key: string, summary?: string }>,
  jiraBaseUrl: string | null,
): string {
  const lines: string[] = [
    `# TEST SET: ${set.summary ? stripMarkers(set.summary) : set.key}`,
    '',
    `**Jira Key:** ${linkTo(set.key, jiraBaseUrl)}`,
    `**Members:** ${members.length}`,
    '',
    '> Test Set membership is Xray-internal (not a Jira issue link). Generated by `bun xray test enrich` — regenerated on every run. Do not edit by hand.',
    '',
    '---',
    '',
    '## Member Tests',
    '',
  ];

  if (members.length === 0) {
    lines.push('_This Test Set has no member Tests._');
  }
  else {
    for (const member of byKey(members)) {
      const summary = member.summary ? ` — ${stripMarkers(member.summary)}` : '';
      lines.push(`- ${linkTo(member.key, jiraBaseUrl)}${summary}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}
